#!/usr/bin/env python3
"""Design an agility-style course as a leg/turn sequence, and emit:

  * gazebo/courses/<name>.course - the waypoint file BOTH the C++ nav and the
    Python mirror read, so there is exactly one definition of the geometry;
  * a course map in the style of an AKC/Westminster judge's map;
  * the geometry report a handler would want: every turn angle, the leg into
    it, and the speed this robot's own measured envelope allows there.

WHY A FILE. mission_geometry.py carries a long comment about C++/Python
mirror drift - makeStar closing its loop in C++ while the Python mirror drew
it open, atom and oval lost from mission_viz's own copy. Every mission here
is written twice and the two copies rot apart. A course read from one file by
both sides cannot drift.

Courses are described the way a handler walks one: a heading change, then a
run to the next obstacle.

  design_course.py NAME "turn,leg turn,leg ..."   (turn in deg, + = right)
"""
import math, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, ".."))
OUTDIR = os.path.join(REPO, "courses")

# --- what this robot can actually do, from ISSUES.md / TERRAIN.md ----------
# Cornering is limited by yaw authority, not traction (see CLAUDE.md's
# steering-rate cap). These are the measured envelope numbers this project
# earned the hard way; the planner enforces its own version at runtime.
A_LAT = 2.5            # m/s^2 lateral budget the planner plans against
V_MAX_FLAT = 3.5       # trotting, flat - marginal above this
V_MAX_ROUGH = 2.0      # walking on rough: the one measured cap (OPEN-7)

def build(seq):
    """seq: [(turn_deg, leg_m), ...] -> waypoints in (north, east)."""
    pts = []
    n = e = 0.0
    hdg = 0.0                      # radians, 0 = due north, + = toward east
    for turn, leg in seq:
        hdg += math.radians(turn)
        n += leg * math.cos(hdg)
        e += leg * math.sin(hdg)
        pts.append((n, e))
    return pts

def corner_radius(p0, p1, p2):
    """Circumradius of three points.

    NOT usable alone near a reversal: for a fold-back the three points are
    nearly collinear and this returns a HUGE radius - i.e. "barely a turn" -
    for the tightest feature on the course. This project has already shipped
    that bug once; README records "a 180 deg reversal reading as kappa~0
    (three collinear points)" as a cause of a real failure. Callers must gate
    on the turn ANGLE, which is what corner_speed() below does.
    """
    ax, ay = p0; bx, by = p1; cx, cy = p2
    a = math.hypot(bx-cx, by-cy); b = math.hypot(ax-cx, ay-cy); c = math.hypot(ax-bx, ay-by)
    s = (a+b+c)/2
    ar = max(1e-9, s*(s-a)*(s-b)*(s-c))
    return (a*b*c) / (4*math.sqrt(ar))

# Yaw authority, not traction, is what caps a corner here (CLAUDE.md: the
# steering-rate cap fix). Above ~150 deg the follower stops trying to arc and
# pivots in place - the acute-vertex behaviour added for the star's 162 deg
# hairpin - so those vertices are scored as pivots, not as arcs.
PIVOT_DEG = 150.0
YAW_MAX = 1.2          # rad/s the body will actually deliver in a turn

def corner_speed(turn_deg, R):
    """(speed, note, kind) for a vertex - angle first, radius second."""
    a = abs(turn_deg)
    if a >= PIVOT_DEG:
        return 0.0, "PIVOT - follower yaws in place", "pivot"
    if R is None:
        return V_MAX_FLAT, "", "straight"
    v_lat = math.sqrt(A_LAT * R)
    v_yaw = YAW_MAX * R                      # v = omega * R
    v = min(V_MAX_FLAT, v_lat, v_yaw)
    note = ""
    if v <= 1.6: note = "TIGHT - planner must brake hard"
    elif v < 2.6: note = "brakes for this"
    lim = "yaw" if v_yaw < v_lat else "a_lat"
    return v, (note + ("  [%s-limited]" % lim) if note else ""), "arc"

def report(name, seq, pts):
    print("  %s - %d waypoints, %.0f m of path" % (name, len(pts),
          sum(l for _, l in seq)))
    print()
    print("   wp  turn    leg     R      v_max(flat)  note")
    prev = (0.0, 0.0)
    allp = [(0.0, 0.0)] + pts
    for i, (turn, leg) in enumerate(seq):
        R = None
        if 0 < i < len(seq) and i+1 < len(allp):
            R = corner_radius(allp[i-1], allp[i], allp[i+1])
        v, note, kind = corner_speed(turn, R)
        print("   %2d  %+5.0f  %5.1f  %s  %s  %s" % (
            i+1, turn, leg,
            ("%6.1f" % R) if R else "  inf ",
            ("%6.2f" % v), note))
    return

def write_course(name, pts, seq):
    os.makedirs(OUTDIR, exist_ok=True)
    p = os.path.join(OUTDIR, name + ".course")
    with open(p, "w") as f:
        f.write("# course: %s\n" % name)
        f.write("# Generated by gazebo/tools/design_course.py - DO NOT hand-edit;\n")
        f.write("# regenerate so the map, the report and the waypoints stay in step.\n")
        f.write("# Read by BOTH WaypointNav::makeCourseFile (C++) and\n")
        f.write("# mission_geometry.py (Python) - one definition, no mirror to drift.\n")
        f.write("# Columns: north_m east_m   (robot frame; leg 1 runs due north)\n")
        f.write("# turn/leg the designer asked for, for provenance:\n")
        f.write("#   %s\n" % " ".join("%g,%g" % (t, l) for t, l in seq))
        for n, e in pts:
            f.write("%.3f %.3f\n" % (n, e))
    return p

if __name__ == "__main__":
    name = sys.argv[1]
    seq = [tuple(float(x) for x in tok.split(",")) for tok in sys.argv[2].split()]
    pts = build(seq)
    report(name, seq, pts)
    print()
    print("  wrote", write_course(name, pts, seq))


# --------------------------------------------------------------------------
# The judge's map. Drawn in the AKC/Westminster convention the operator sent:
# a metre grid, numbered obstacles in circles, the running order implied by
# the numbers, and a title block. Colour is used for one thing only - what
# the PRE-PLANNER does to the speed - because that is the question this
# course was built to ask.
def draw_map(name, pts, seq, out_png, title, subtitle, plan=None):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Circle

    allp = [(0.0, 0.0)] + list(pts)
    ee = [p[1] for p in allp]; nn = [p[0] for p in allp]
    pad = 6
    fig, ax = plt.subplots(figsize=(13, 8.5))
    ax.set_xlim(min(ee) - pad, max(ee) + pad)
    ax.set_ylim(min(nn) - pad, max(nn) + pad)
    ax.set_aspect("equal")
    ax.set_xticks(range(int((min(ee) - pad) // 10 * 10), int(max(ee) + pad) + 10, 10))
    ax.set_yticks(range(int((min(nn) - pad) // 10 * 10), int(max(nn) + pad) + 10, 10))
    ax.grid(True, color="#cccccc", lw=0.8)
    ax.tick_params(labelsize=8)

    # the running line
    ax.plot(ee, nn, "-", color="#444444", lw=1.4, zorder=2)

    # start / finish, in the maps' own vocabulary
    ax.add_patch(Circle((allp[0][1], allp[0][0]), 1.5, fc="white", ec="black", lw=1.5, zorder=4))
    ax.text(allp[0][1], allp[0][0], "S", ha="center", va="center", fontsize=10, fontweight="bold", zorder=5)
    ax.add_patch(Circle((allp[-1][1], allp[-1][0]), 1.5, fc="white", ec="black", lw=1.5, zorder=4))
    ax.text(allp[-1][1], allp[-1][0], "F", ha="center", va="center", fontsize=10, fontweight="bold", zorder=5)

    for i, (turn, leg) in enumerate(seq):
        n, e = pts[i]
        R = corner_radius(allp[i], allp[i+1], allp[i+2]) if i + 2 < len(allp) else None
        v, note, kind = corner_speed(turn, R)
        col = {"pivot": "#c0392b", "arc": "#2c7fb8", "straight": "#7f8c8d"}[kind]
        if kind == "arc" and v >= V_MAX_FLAT - 0.01: col = "#27ae60"
        ax.add_patch(Circle((e, n), 1.6, fc="white", ec=col, lw=2.0, zorder=4))
        ax.text(e, n, str(i + 1), ha="center", va="center", fontsize=9,
                fontweight="bold", color=col, zorder=5)
        if kind == "pivot":
            ax.annotate("180°", (e, n), textcoords="offset points", xytext=(0, 14),
                        ha="center", fontsize=8, color=col, fontweight="bold")
        elif v < 2.6:
            ax.annotate("%.1f" % v, (e, n), textcoords="offset points", xytext=(0, -18),
                        ha="center", fontsize=7.5, color=col)

    ax.set_title(title, fontsize=13, fontweight="bold")
    ax.text(0.5, 1.015, subtitle, transform=ax.transAxes, ha="center", fontsize=9)
    ax.set_xlabel("east (m)", fontsize=9); ax.set_ylabel("north (m)", fontsize=9)
    legend = ("green = planner runs full speed    blue = planner brakes for the turn "
              "   red = 180° pivot, follower yaws in place")
    ax.text(0.5, -0.085, legend, transform=ax.transAxes, ha="center", fontsize=8.5)
    if plan:
        ax.text(0.5, -0.125, plan, transform=ax.transAxes, ha="center", fontsize=8.5,
                fontweight="bold")
    fig.tight_layout()
    fig.savefig(out_png, dpi=130, bbox_inches="tight")
    return out_png
