#!/usr/bin/env python3
"""OPEN-6: isolate the BOOT SEQUENCE and find what makes it go non-finite.

Operator-ordered (2026-08-28): "look at JUST the sequence it has issues
with under different scenarios (including artificial system load that we
control)."

So this runs the shortest mission the catalog allows - the boot window is
~20 s and dominates it - and reads the RAW ctrl log for the newly-added
`NONFINITE-FIELDS` line, which names the offending field, the elapsed
time and the control iteration. One factor is varied per cell; everything
else is held at the shipping default. Rows land in
unittests/boot_blips.csv.

Load is generated by this script (N spinning python subprocesses, killed
after the run) so "artificial system load we control" is genuinely
controlled and recorded per row, not inferred afterwards.
"""
import argparse, csv, os, re, subprocess, sys, time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
RUNNER = os.path.join(ROOT, "stm32mp1/gazebo/conductor/mission_runner.py")
CSV_PATH = os.path.join(HERE, "boot_blips.csv")
CTRL_LOG = "/tmp/cheetah_conductor/ctrl_0.log"

FIELD_RE = re.compile(r"NONFINITE-FIELDS \((\d+)\) t=([\d.]+) iter=(\d+) bad: ([^|]*)\|")


def spinners(n):
    return [subprocess.Popen([sys.executable, "-c", "while True: pass"],
                              stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            for _ in range(n)]


def run_cell(terrain, gait, speed, load, extra):
    procs = spinners(load)
    try:
        cmd = [sys.executable, RUNNER, "--terrain", terrain, "--slot", "dash:5",
               "--gait", gait, "--speed", str(speed), "--dash", "0",
               "--no-chase", "--extra", extra]
        p = subprocess.run(cmd, capture_output=True, text=True)
    finally:
        for q in procs:
            q.kill()
    try:
        log = open(CTRL_LOG, errors="ignore").read()
    except OSError:
        log = ""
    hits = FIELD_RE.findall(log)
    verdict = ("PASS" if "mission result: PASS" in (p.stdout + p.stderr)
               else "FELL" if "FELL" in (p.stdout + p.stderr) else "OTHER")
    return dict(blips=len(hits),
                fields=";".join(sorted({h[3].strip() for h in hits})) or "-",
                first_t=hits[0][1] if hits else "",
                first_iter=hits[0][2] if hits else "",
                verdict=verdict)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--reps", type=int, default=3)
    args = ap.parse_args()
    # ONE factor varied per row against the shipping baseline.
    cells = []
    for load in (0, 4, 8):
        cells.append(dict(name="load%d" % load, terrain="flat", gait="walking",
                           speed=1.5, load=load, extra="WP_CLOSE_LEG=0"))
    cells += [
        dict(name="mud", terrain="mud", gait="walking", speed=1.5, load=0,
             extra="WP_CLOSE_LEG=0"),
        dict(name="rough", terrain="rough", gait="walking", speed=1.5, load=0,
             extra="WP_CLOSE_LEG=0"),
        dict(name="gait_trotRunning", terrain="flat", gait="trotRunning",
             speed=1.5, load=0, extra="WP_CLOSE_LEG=0"),
        dict(name="aiding_off", terrain="flat", gait="walking", speed=1.5,
             load=0, extra="WP_CLOSE_LEG=0 SIM_VEL_AIDING=0"),
    ]
    new = not os.path.exists(CSV_PATH)
    with open(CSV_PATH, "a", newline="") as f:
        w = csv.writer(f)
        if new:
            w.writerow(["cell", "terrain", "gait", "speed", "load_spinners",
                        "rep", "blips", "fields", "first_t_s", "first_iter",
                        "verdict", "when"])
        for c in cells:
            for rep in range(1, args.reps + 1):
                r = run_cell(c["terrain"], c["gait"], c["speed"], c["load"],
                             c["extra"])
                w.writerow([c["name"], c["terrain"], c["gait"], c["speed"],
                            c["load"], rep, r["blips"], r["fields"],
                            r["first_t"], r["first_iter"], r["verdict"],
                            time.strftime("%Y-%m-%d %H:%M:%S")])
                f.flush()
                print("[boot] %-16s rep%d load=%d -> blips=%d fields=%s "
                      "t=%s iter=%s (%s)"
                      % (c["name"], rep, c["load"], r["blips"], r["fields"],
                         r["first_t"] or "-", r["first_iter"] or "-",
                         r["verdict"]), flush=True)
                time.sleep(3)
    print("BOOT_PROBE_DONE", flush=True)


if __name__ == "__main__":
    main()
